# ---------------------------------------- #
#         __                    _          #
#        / /_  ____ ___________(_)___      #
#       / __ \/ __ `/ ___/ ___/ / __ \     #
#      / / / / /_/ (__  |__  ) / /_/ /     #
#     /_/ /_/\__,_/____/____/_/\____/      #
#                                          #
# ---------------------------------------- #



# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace: !nclude specific/lovelace/lovelace.yaml
 


# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# asuswrt configuration
asuswrt: !include specific/asuswrt.yaml


# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
